/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../src/components/Auth/index.vue')['default']
    AuthAll: typeof import('./../src/components/AuthAll/index.vue')['default']
    copy: typeof import('./../src/components/Auth copy/index.vue')['default']
    IEpMagicStick: typeof import('~icons/ep/magic-stick')['default']
    IIonArrowRedo: typeof import('~icons/ion/arrow-redo')['default']
    NoticeSlide: typeof import('./../src/components/NoticeSlide/index.vue')['default']
    NumberScroll: typeof import('./../src/components/NumberScroll/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    XtDialog: typeof import('./../src/components/XtDialog/index.vue')['default']
  }
}
